name: learn-github-actions
on: [push]
jobs:
  branches-ignore:
        - 'master'
    check-python-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - run: python -m pip install --upgrade pip
        - run: python --version
